services:
  postgres_db:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../.env
    restart: always
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports: 
      - 8080:80
    env_file:
      - ../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin   # ✅ persists pgAdmin settings
    depends_on:
      - postgres_db
    restart: always
    networks:
      - database

volumes:
  postgres_data: 
  pgadmin_data:
networks:
  database:
    driver: bridge
